---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Servarr:
    - Radarr:
        href: https://radarr.phoenix-server.cc
        description: Homepage is awesome
    - Sonarr:
        href: https://sonarr.phoenix-server.cc
    - Lidarr:
        href: https://lidarr.phoenix-server.cc
    - Readarr:
        href: https://readarr.phoenix-server.cc

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is ðŸ˜Ž
